---
- name: AWX 템플릿 배포
  hosts: genie_vm
  vars:
    base_path: 'genie'
    genie_ip: 'localhost'
  gather_facts: no
  tasks:

  - name: AWX 초기 관리자 패스워드 추출
    shell: kubectl get -n awx secret awx-admin-password -o jsonpath="{.data.password}" | base64 --decode
    register: admin_password

  # Wordpress
  - name: Create wordpress deploy playbook
    awx.awx.job_template:
      name: wordpress_deploy
      job_type: "run"
      inventory: genie_inventory
      project: playbook_project
      playbook: wordpress/wordpress_deploy.yml
      credentials:
        - "automation_controller_credential"
      state: "present"
      controller_host: "http://{{ genie_ip }}:80"
      controller_username: admin
      controller_password: "{{ admin_password.stdout }}"
      extra_vars: 
        instance_temp: "CentOS-8-cloudinit"
        instance_computeoffer: "2C-4GB-RBD"

  - name: Create wordpress state check playbook
    awx.awx.job_template:
      name: wordpress_check
      job_type: "run"
      inventory: genie_inventory
      project: playbook_project
      playbook: wordpress/wordpress_check.yml
      credentials:
        - "automation_controller_credential"
      state: "present"
      controller_host: "http://{{ genie_ip }}:80"
      controller_username: admin
      controller_password: "{{ admin_password.stdout }}"

  # - name: Create wordpress delete playbook
  #   awx.awx.job_template:
  #     name: wordpress_destroy
  #     job_type: "run"
  #     inventory: genie_inventory
  #     project: playbook_project
  #     playbook: wordpress/wordpress_destroy.yml
  #     credentials:
  #       - "automation_controller_credential"
  #     state: "present"
  #     controller_host: "http://{{ genie_ip }}:80"
  #     controller_username: admin
  #     controller_password: "{{ admin_password.stdout }}"
      
  # Nextcloud
  - name: Create nextcloud deploy playbook
    awx.awx.job_template:
      name: nextcloud_deploy
      job_type: "run"
      inventory: genie_inventory
      project: playbook_project
      playbook: nextcloud/nextcloud_deploy.yml
      credentials:
        - "automation_controller_credential"
      state: "present"
      controller_host: "http://{{ genie_ip }}:80"
      controller_username: admin
      controller_password: "{{ admin_password.stdout }}"
      extra_vars: 
        instance_temp: "CentOS-8-cloudinit"
        instance_computeoffer: "2C-4GB-RBD"

  - name: Create nextcloud state check playbook
    awx.awx.job_template:
      name: nextcloud_check
      job_type: "run"
      inventory: genie_inventory
      project: playbook_project
      playbook: nextcloud/nextcloud_check.yml
      credentials:
        - "automation_controller_credential"
      state: "present"
      controller_host: "http://{{ genie_ip }}:80"
      controller_username: admin
      controller_password: "{{ admin_password.stdout }}"

  - name: Create nextcloud delete playbook
    awx.awx.job_template:
      name: nextcloud_destroy
      job_type: "run"
      inventory: genie_inventory
      project: playbook_project
      playbook: nextcloud/nextcloud_destroy.yml
      credentials:
        - "automation_controller_credential"
      state: "present"
      controller_host: "http://{{ genie_ip }}:80"
      controller_username: admin
      controller_password: "{{ admin_password.stdout }}"

  # 3Tier
  - name: Create 3tier deploy playbook
    awx.awx.job_template:
      name: tier_deploy
      job_type: "run"
      inventory: genie_inventory
      project: playbook_project
      playbook: 3tier/tier_deploy.yml
      credentials:
        - "automation_controller_credential"
      state: "present"
      controller_host: "http://{{ genie_ip }}:80"
      controller_username: admin
      controller_password: "{{ admin_password.stdout }}"
      extra_vars: 
        instance_temp: "CentOS-8-cloudinit"
        instance_computeoffer: "2C-4GB-RBD"

  - name: Create 3tier state check playbook
    awx.awx.job_template:
      name: tier_check
      job_type: "run"
      inventory: genie_inventory
      project: playbook_project
      playbook: 3tier/tier_check.yml
      credentials:
        - "automation_controller_credential"
      state: "present"
      controller_host: "http://{{ genie_ip }}:80"
      controller_username: admin
      controller_password: "{{ admin_password.stdout }}"

  - name: Create 3tier delete playbook
    awx.awx.job_template:
      name: tier_destroy
      job_type: "run"
      inventory: genie_inventory
      project: playbook_project
      playbook: 3tier/tier_destroy.yml
      credentials:
        - "automation_controller_credential"
      state: "present"
      controller_host: "http://{{ genie_ip }}:80"
      controller_username: admin
      controller_password: "{{ admin_password.stdout }}"    