---
- name: test
  hosts: localhost
  gather_facts: no
  tasks:

  - name: Create a Genie remote repository project
    uri:
      url: http://10.10.1.69:80/api/v2/execution_environments/
      method: POST
      body_format: json
      user: admin
      password: password
      force_basic_auth: yes
      body:
        {
          "name": AWX EE (genie_latest),
          "image": ablecloudteam/genie-awx-ee
        }
      status_code: 201
