---
- name: test
  hosts: localhost
  gather_facts: no
  tasks:

  - name: Add EE to the controller instance
    awx.awx.execution_environment:
      name: "AWX EE (genie_latest)"
      image: ablecloudteam/genie-awx-ee
