---
- name: Genie를 활용한 Mold VM 배포
  hosts: mold_10.10.1.10
  gather_facts: no
  tasks:

##### Deploy VirtualMachine #####

    - name: 가상머신 생성
      cs_instance:
        name: sj-deploy-vm1
        template: CentOS8.4_changeRepo
        service_offering: 2C-4GB-RBD
        networks:
          - sj-genie-network1
      delegate_to: localhost
