---
- name: Genie를 활용한 Mold VM 삭제
  hosts: localhost
  vars:
    instance_nm: 'nextcloud-deploy-vm'
    service_group: 'Nextcloud'
  gather_facts: no
  tasks:
##### delete resource package  #####
    # - name: 서비스 그룹 상태정보 삭제 및 단위별 상태정보 삭제
    #   ansible.builtin.command: python2 /home/runner/mold_genie_api.py \
    #     -c deleteDeployedResourceGroup \
    #     -ap http -ip "{{ lookup('env', 'MOLD_DEFAULT_URL') }}" -p "{{ lookup('env', 'MOLD_DEFAULT_PORT') }}" \
    #     -ak "{{ lookup('env', 'MOLD_API_KEY') }}" \
    #     -sk "{{ lookup('env', 'MOLD_SECRET_KEY') }}" \
    #     -zid "{{ lookup('env', 'MOLD_ZONE_ID') }}" \
    #     -n "{{ service_group }}"

    - name: 배포한 가상머신 정보 수집
      cs_instance_info:
        api_url: "{{ lookup('env', 'MOLD_API_URL') }}"
        api_key: "{{ lookup('env', 'MOLD_API_KEY') }}"
        api_secret: "{{ lookup('env', 'MOLD_SECRET_KEY') }}"
        name: "{{ instance_nm }}"
      delegate_to: localhost
      register: vm

    - name: 배포 가상머신 ip 정보 수집
      debug:
        msg: "{{ vm }}"
