---
- name: State Httpd
  hosts: localhost
  gather_facts: no
  tasks:
##### Deploy VirtualMachine #####

    - name: 배포한 가상머신 정보 수집
      cs_instance_info:
        api_url: "{{ lookup('env', 'MOLD_API_URL') }}"
        api_key: "{{ lookup('env', 'MOLD_API_KEY') }}"
        api_secret: "{{ lookup('env', 'MOLD_SECRET_KEY') }}"
        name: nextcloud-deploy-vm
      delegate_to: localhost
      register: vm

    - name: 배포 가상머신 ip 정보 수집
      debug:
        msg: "{{ vm.instances[0].nic[0].ipaddress }}"

    - name: register resource
      ansible.builtin.command: "python2 /home/runner/cs_api.py -c listAutomationDeployedResource -ip 10.10.254.168 -ak ArfB-Y2r8LXfeWBmyNzpCgk1aOzg2s_O8PYXLX6uNRKg7lOWyd16nTshg4fsmEWs0dnEk8PIb0do0eczlysFpg -sk g8Cghfff4Fc-n_iEYoHDJxnIv6sB0wJFx1CwtgEvBwJZw-W41Dblg7FA-oWN_EfO_C__f90STJDOPwlx3ftkUg -n ServiceName2"

    # - debug: var=services_state.ansible_facts.services["httpd.service"].state
    # - debug: var=services_state.ansible_facts.services["mysqld.service"].state